pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from ..forms import AnswerForm
from pybo.models import Question, Answer
from pybo.views.auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id): # answer.create
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=question_id), answer.id))
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/modify/<int:answer_id>', methods=('GET','POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)

    if g.user != answer.user:
        flash('수정 권한이 없습니다.')
        return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=answer.question.id), answer.id))
    
    if request.method == 'POST':
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()
            db.session.commit()
            return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=answer.question.id), answer.id))

    else:
        form = AnswerForm(obj=answer)
    
    return render_template('answer/answer_form.html', answer=answer, form=form)

@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)

    if g.user != answer.user:
        flash('삭제 권한이 없습니다.')
        return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=answer.question.id), answer.id))
    
    question_id = answer.question.id # 먼저 question_id를 얻어놓고 삭제해야 한다.
    db.session.delete(answer)
    db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

# 답변 추천 기능
@bp.route('/like/<int:answer_id>')
@login_required
def like(answer_id):
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        flash('본인이 작성한 답변은 추천할 수 없습니다.')
    elif g.user in _answer.voter:
        _answer.voter.remove(g.user)
        db.session.commit()
    else:
        _answer.voter.append(g.user)
        db.session.commit()
    return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=_answer.question.id), _answer.id))

pybo/views/comment_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import CommentForm
from pybo.models import Question, Answer, Comment
from pybo.views.auth_views import login_required
import random

bp = Blueprint('comment', __name__, url_prefix='/comment')

# 질문 댓글 기능
@bp.route('/create/question/<int:question_id>', methods=('POST','GET'))
# @login_required
def create_question(question_id):
    form = CommentForm()
    question = Question.query.get_or_404(question_id)
    get_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
    if request.method == 'POST' and form.validate_on_submit():
        if g.user:   
            comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), question=question, ip=get_ip)
        elif not g.user:
            comment = Comment(ip=get_ip, content=form.content.data, create_date=datetime.now(), question=question)
        
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=question_id))
    return render_template('comment/comment_form.html', form=form)

@bp.route('/modify/question/<int:comment_id>')
@login_required
def modify_question(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('수정권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=comment.question.id))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=comment.question.id))
    else:
        form = CommentForm(obj=comment)
    return render_template('comment/comment_form.html', form=form)

@bp.route('/delete/question/<int:comment_id>')
@login_required
def delete_question(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    question = Question.query.get_or_404(comment.question.id)
    if g.user != comment.user and g.user != question.user: # 질문 작성자도 삭제 가능
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=comment.question.id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('question.detail', question_id=comment.question.id))

# 답변 댓글 기능
@bp.route('/create/answer/<int:answer_id>', methods=('POST','GET'))
# @login_required
def create_answer(answer_id):
    form = CommentForm()
    answer = Answer.query.get_or_404(answer_id)
    get_ip = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
    if request.method == 'POST' and form.validate_on_submit():
        if g.user:   
            comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), answer=answer, ip=get_ip)
        elif not g.user:
            comment = Comment(ip=get_ip, content=form.content.data, create_date=datetime.now(), answer=answer)
        
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('question.detail', question_id=answer.question.id))
    return render_template('comment/comment_form.html', form=form)

@bp.route('/modify/answer/<int:comment_id>')
@login_required
def modify_answer(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('수정권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=comment.question.id))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=comment.question.id))
    else:
        form = CommentForm(obj=comment)
    return render_template('comment/comment_form.html', form=form)

@bp.route('/delete/answer/<int:comment_id>')
@login_required
def delete_answer(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    answer = Answer.query.get_or_404(comment.answer.id)
    question = Question.query.get_or_404(answer.question.id)
    if g.user != comment.user and g.user != answer.user and g.user != question.user:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=comment.question.id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('question.detail', question_id=comment.question.id))

pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash, jsonify
from werkzeug.utils import redirect

from .. import db
from pybo.models import Question, Answer, User, answer_voter, question_voter
from pybo.forms import QuestionForm, AnswerForm, CommentForm
from pybo.views.auth_views import login_required
from sqlalchemy import func

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/')
def _list(): # list는 파이썬 내장 함수이므로 함수명을 _list로 정의
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    sort = request.args.get('sort', type=str, default='recent')
    # 정렬 기능 : outerjoin() 함수를 사용하여 추천수 및 답변이 없는 질문도 포함A
    if sort == 'popular':
        question_list = Question.query.outerjoin(question_voter).group_by(Question).order_by(func.count(question_voter.c.user_id).desc())
    elif sort == 'answer':
        question_list = Question.query.outerjoin(Answer).group_by(Question).order_by(func.count(Answer.id).desc())
    else:
        question_list = Question.query.order_by(Question.create_date.desc())
    # 검색 기능
    if kw:
        search = '%%{}%%'.format(kw) # %%는 %를 문자 자체로 인식하게 함
        # Subquery
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username) \
            .join(User, Answer.user_id == User.id).subquery() # 서브쿼리를 사용하여 답변 테이블과 사용자 테이블을 조인
        question_list = question_list \
            .join(User) \
            .outerjoin(sub_query, sub_query.c.question_id == Question.id) \
            .filter(Question.subject.ilike(search) |
                    Question.content.ilike(search) | 
                    User.username.ilike(search) | 
                    sub_query.c.content.ilike(search) | 
                    sub_query.c.username.ilike(search) 
                    ) \
            .distinct() # 중복 제거

    question_list = question_list.paginate(page=page, per_page=10) # 10개씩 보여주기

    return render_template('question/question_list.html', question_list=question_list, page=page, kw=kw, sort=sort)

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    # paginate answer
    question = Question.query.get_or_404(question_id)
    page = request.args.get('page', type=int, default=1)
    sort = request.args.get('sort', type=str, default='recent')
    # 정렬 기능
    if sort == 'popular' and question.answer_set :
        answer_list =  Answer.query.filter(Answer.question_id == question_id).\
                  outerjoin(answer_voter).\
                  group_by(Answer).\
                  order_by(func.count(answer_voter.c.user_id).desc()) # func.count()는 SQL의 count() 함수를 의미, outerjoin으로 추천수가 없는 답변도 포함
    else:
        answer_list = Answer.query.filter(Answer.question_id == question_id).order_by(Answer.create_date.desc())
    answer_list = answer_list.paginate(page=page, per_page=5)
    form = AnswerForm()

    return render_template('question/question_detail.html', question=question, form=form, answer_list=answer_list, sort=sort)                                                                               

@bp.route('/create/', methods = ('GET','POST'))
@login_required
def create():
    form = QuestionForm()

    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index')) # POST(질문 등록) 방식에는 데이터베이스 처리
    
    return render_template('question/question_form.html', form=form)

@bp.route('/modify/<int:question_id>', methods=('GET','POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)

    if g.user != question.user:
        flash('수정 권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))
    
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question) # form에서 받은 데이터를 question 객체에 적용
            question.modify_date = datetime.now() # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
        
    else: # GET 방식일 때
        form = QuestionForm(obj=question)

    return render_template('question/question_form.html', form=form) # GET 방식일 때는 question 객체를 form에 적용하여 전달

@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제 권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

# 질문 추천 라우팅 함수
@bp.route('/like/<int:question_id>/')
@login_required
def like(question_id):
    _question = Question.query.get_or_404(question_id)
    # 본인 글 추천 불가
    if g.user == _question.user:
        flash('본인 글은 추천할 수 없습니다.')
    # 추천한 적이 있으면 추천 취소
    elif g.user in _question.voter:
        _question.voter.remove(g.user)
        db.session.commit()
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <!-- flash error -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|markdown }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge text-dark p-2 text-end">
                    <div class="mb-2">{{ question.user.username }}</div>
                    {% if question.modify_date %}
                    <div>{{ question.create_date|datetime }} (수정 : {{ question.modify_date|datetime}})</div>
                    {% else %}
                    <div>{{ question.create_date|datetime }}</div>
                    {% endif %}
                </div>
            </div>
            <div class="my-3">
                <!--질문 추천-->
                {% if g.user %}
                <a href="javascript:void(0)" class="btn btn-sm btn-outline-secondary" name="like-q" data-uri="{{ url_for('question.like', question_id=question.id) }}">
                    추천
                    <span class="badge rounded-pill bg-success text-light align-middle" id="like-q-count">{{ question.voter|length }}</span>
                </a>
                {% endif %}
                <!--질문 수정 및 삭제-->
                {% if g.user and g.user == question.user %}
                <a href="{{ url_for('question.modify', question_id=question.id) }}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" name="delete-q" class="delete btn btn-sm btn-outline-secondary" data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
                {% endif %}
            </div>
            <!--질문 댓글 기능-->
            {% if question.comment_set|length > 0 %}
            <div class="mt-3">
                {% for comment in question.comment_set %}
                <div class="comment py-2 text-muted">
                    <span>{{ comment.content }}</span>
                    <span>
                        {% if comment.user.id %}
                        - {{ comment.user.username }} , {{ comment.create_date|datetime }}
                        {% else %}
                        - {{ comment.ip }} , {{ comment.create_date|datetime }}
                        {% endif %}
                        {% if comment.modify_date %}
                        (수정: {{ comment.modify_date|datetime }})
                        {% endif %}
                    </span>
                    {% if (g.user and g.user == comment.user) or (g.user == question.user) %}
                    <a href="{{ url_for('comment.modify_question', comment_id=comment.id) }}" class="small">수정</a>
                    <a href="#" class="small delete" data-uri="{{ url_for('comment.delete_question', comment_id=comment.id) }}">삭제</a>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <!--질문 댓글 작성-->
            <div>
                <a href="{{ url_for('comment.create_question', question_id=question.id) }}" class="small text-decoration-none text-info">댓글 작성</a>
            </div>
            <!--질문 댓글 기능 종료-->
        </div>
    </div>
    <!--답변-->
    <!--정렬 옵션-->
    <div class="row justify-content-between my-2 border-bottom">
        <h5 class="col-6">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
        <!-- sorting select button -->
        <div class="col-3 mp-2">
            <select class="form-select sort" id="a-sort">
                <option value="recent" {% if sort == 'recent' %} selected {% endif %}>최신순</option>
                <option value="popular" {% if sort == 'popular' %} selected {% endif %}>추천순</option>
            </select>
        </div>
    </div>    
    
    {% for answer in answer_list %}
    <div class="card my-3">
        <a id ="answer_{{ answer.id }}"></a> <!--Anchor-->
        <div class="card-body" style="height: fit-content;">
            <div class="card-text">{{ answer.content|markdown }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.user.username }}</div>
                    <div>{{ answer.create_date|datetime }}</div>
                </div>
            </div>
            <div class="my-3">
                <!--답변 추천-->
                {% if g.user %}
                <a href="javascript:void(0)" class="btn btn-sm btn-outline-secondary" name="like-a" data-uri="{{ url_for('answer.like', answer_id=answer.id) }}">
                    추천
                    <span class="badge rounded-pill bg-success text-light align-middle" id="like-a-count">{{ answer.voter|length }}</span>
                </a>
                {% endif %}
                <!--답변 수정 및 삭제-->
                {% if g.user and g.user == answer.user %}
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" name="delete-a" class="delete btn btn-sm btn-outline-secondary" data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                {% endif %}
            </div>
            <!--답변 댓글 기능-->
            {% if answer.comment_set|length > 0 %}
            <div class="mt-3">
                {% for comment in answer.comment_set %}
                <div class="comment py-2 text-muted">
                    <span>{{ comment.content }}</span>
                    <span>
                        {% if comment.user.id %}
                        - {{ comment.user.username }} , {{ comment.create_date|datetime }}
                        {% else %}
                        - {{ comment.ip }} , {{ comment.create_date|datetime }}
                        {% endif %}
                        {% if comment.modify_date %}
                        (수정: {{ comment.modify_date|datetime }})
                        {% endif %}
                    </span>
                    {% if (g.user and g.user == comment.user) or (g.user == answer.user) or (g.user == question.user) %}
                    <a href="{{ url_for('comment.modify_answer', comment_id=comment.id) }}" class="small">수정</a>
                    <a href="#" class="small delete" data-uri="{{ url_for('comment.delete_answer', comment_id=comment.id) }}">삭제</a>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
            {% endif %}
            <!--답변 댓글 작성-->
            <div>
                <a href="{{ url_for('comment.create_answer', answer_id=answer.id) }}" class="small text-decoration-none text-info">댓글 작성</a>
            </div>
            <!--답변 댓글 기능 종료-->
        </div>
    </div>
    {% endfor %}
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if answer_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ answer_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        {% for page_num in answer_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != answer_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if answer_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ answer_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <form id="searchForm" method="get" action="{{ url_for('question.detail', question_id=question.id) }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
        <input type="hidden" id="sort" name="sort" value="{{ sort }}">
    </form>

    <!-- 답변 등록 -->
    <h5 class="border-bottom my-1 py-1">새 답변 등록</h5>
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-sm-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert"> 
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-1">
            <textarea {% if not g.user %}disabled{% endif %} 
            class="form-control" name="content" id="content" rows="10">
            {{ form.content.data or '' }}</textarea>
            {{ simplemde.load }}
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const question_delete = document.getElementsByName('delete-q');
    if (question_delete) {
        Array.from(question_delete).forEach((el) => {
            el.addEventListener('click', () => {
                if (confirm('질문을 삭제하시겠습니까?')) {
                    location.href = el.dataset.uri;
                }
            });
        });
    }

    const answer_delete = document.getElementsByName('delete-a');
    if (answer_delete) {
        Array.from(answer_delete).forEach((el) => {
            el.addEventListener('click', () => {
                if (confirm('답변을 삭제하시겠습니까?')) {
                    location.href = el.dataset.uri;
                }
            });
        });
    }

    const like_q = document.getElementsByName('like-q');
    if (like_q) {
        Array.from(like_q).forEach((el) => {
            el.addEventListener('click', () => {
                location.href = el.dataset.uri;
            });
        });
    }

    const like_a = document.getElementsByName('like-a');
    if (like_a) {
        Array.from(like_a).forEach((el) => {
            el.addEventListener('click', () => {
                location.href = el.dataset.uri;
            });
        });
    }

    const page_elements = document.getElementsByClassName('page-link');
    Array.from(page_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            const page = this.getAttribute('data-page');
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });

    // when sort select box with id sort changed, change selected value and submit form

    const sort_answer = document.getElementById('a-sort');
    if (sort_answer) {
        sort_answer.addEventListener('change', function () {
            const sort_input = document.getElementById('sort');
            sort_input.value = this.value;
            document.getElementById('searchForm').submit();
        });
    }

    // 질문 댓글 삭제
    const comment_delete = document.getElementsByClassName('small delete');
    if (comment_delete) {
        Array.from(comment_delete).forEach((el) => {
            el.addEventListener('click', () => {
                if (confirm('댓글을 삭제하시겠습니까?')) {
                    location.href = el.dataset.uri;
                }
            });
        });
    }

</script>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %} <!--base.html 상속-->
{% block content %}
<!-- 질문 목록 -->
<div class="container my-3">
    <!--정렬 및 질문등록-->
    <div class="row justify-content-between my-2">
        <div class="col-3 mp-2">
            <select class="form-select sort" id="q-sort">
                <option value="recent" {% if sort == 'recent' %} selected {% endif %}>최신순</option>
                <option value="popular" {% if sort == 'popular' %} selected {% endif %}>추천순</option>
                <option value="answer" {% if sort == 'answer' %} selected {% endif %}>답변순</option>
            </select>
        </div>
        <div class="col-4">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>추천</th>
            <th style="width:50%">제목</th> <!--가운데 정렬-->
            <th>작성자</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list.items %}
        <tr class="text-center">
            <td>{{ question.voter|length }}</td> 
            <td class="text-start">
                <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger ml-2">[답변 {{ question.answer_set|length }}]</span>
                {% endif %}
            </td>
            <td>{{ question.user.username }}</td> <!--User added-->
            <td>{{ question.create_date|datetime}}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!--질문 등록-->
    <div>
        <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
    </div>
</div>
    <!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if question_list.has_prev %}
    <li class="page-item">
        <a class="page-link" data-page="{{ question_list.prev_num }}" href="javascript:void(0)">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
    </li>
    {% endif %}
    {% for page_num in question_list.iter_pages() %}
    {% if page_num %}
    {% if page_num != question_list.page %}
    <li class="page-item">
        <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
    </li>
    {% else %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="#">{{ page_num }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled">
        <a class="page-link" href="javascript:void(0)">...</a>
    </li>
    {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
        <a class="page-link" data-page="{{ question_list.next_num }}" href="javascript:void(0)">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
    </li>
    {% endif %}
</ul>
<!-- 페이징처리 끝 -->

<!--SearchForm-->
<form id="searchForm" method="get" action="{{ url_for('question._list') }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="sort" name="sort" value="{{ sort }}">
</form>
{% endblock %}
{% block script %}
<script type="text/javascript">
    const page_elements = document.getElementsByClassName('page-link');
    Array.from(page_elements).forEach(function (element) {
        element.addEventListener('click', function () {
            const page = this.getAttribute('data-page');
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    const btn_search = document.getElementById('btn_search');
    btn_search.addEventListener('click', function () {
        const search_kw = document.getElementById('search_kw');
        document.getElementById('kw').value = search_kw.value;
        document.getElementById('page').value = 1; // 검색시 페이지를 1페이지로 초기화
        document.getElementById('searchForm').submit();
    });

    const sort_question = document.getElementById('q-sort');
    if (sort_question) {
        sort_question.addEventListener('change', function () {
            const sort_input = document.getElementById('sort');
            sort_input.value = this.value;
            document.getElementById('searchForm').submit();
        })
    }
</script>
{% endblock %}